spring:
  application:
    name: sora
  datasource:
    username: root
    password: sorasora520
  #username: sa
    #password: kasuganosora520
    #url: jdbc:sqlserver://localhost:1433;database=Blog
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #data:
    url: jdbc:mysql://127.0.0.1:3306/sora_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=1000,expireAfterAccess=60s

mybatis-plus:
  type-aliases-package: com.vincent.admin.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 关闭驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出sql语句,测试
  global-config:
    db-config:
      table-underline: false
      id-type: auto # 主键类型
    banner: false

server:
  port: 9527
