spring:
  freemarker:
    suffix: .html
    enabled: true
    cache: false
    charset: UTF-8
    content-type: text/html
    allow-session-override: false
  mail:
    host: smtp.yandex.com #smtp.qq.com
    username: no-reply@sora.vin #1359643068@qq.com
    password: sorasora520 #linjdojcyburhbch
    port: 25 #587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: true
    protocol: smtp
  servlet:
    multipart:
      max-request-size: 10MB #限制上传的多个文件的总大小
      max-file-size: 2MB
  application:
    name: sora
  datasource:
    username: root
    password: sorasora520
    url: jdbc:mysql://127.0.0.1:3306/sora_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=true&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    port: 6379
    #password: kasugano
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间 负值表示无限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        min-idle: 0
    timeout: 100
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=1000,expireAfterAccess=60s
  rabbitmq:
    username: VincentTsai
    password: sorasora520
    virtual-host: /
    host: 127.0.0.1
    port: 5672

mybatis-plus:
  type-aliases-package: com.vincent.admin.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 关闭驼峰命名
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出sql语句,测试
  global-config:
    db-config:
      table-underline: false
      id-type: auto # 主键类型
    banner: false

server:
  port: 9527
file:
  upload-folder: /home/vincent/blog-upload/
  static-path: /** # 静态资源对外暴露的访问路径 upload-images

